---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - name: set a cron for ansible-pull at 2am
    cron:
            name: "pull at 2am"
            user: sysadmin
            hour: 2
            job: "/usr/bin/ansible-pull -o -d ~/.ansible -U https://github.com/bhewer/ansible.git -i hosts update.yml"
