---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - name: set a cron for ansible-pull every 15 minutes
    cron:
            name: "pull at reboot"
            user: sysadmin
            minute: */3
            job: "ansible-pull -o -U https://github.com/bhewer/ansible.git -i hosts update.yml"
