---
- import_playbook: ldap.yml
- import_playbook: packages.yml
- import_playbook: update_network/reconfigure.yml
- import_playbook: mount.yml

- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - name: create systemd unit for ansible-pull
    template:
            src: "update_shutdown.j2"
            dest: "/etc/systemd/system/update_shutdown.service"

  - name: create systemd unit for update network config
    template:
            src: "update_network.j2"
            dest: "/etc/systemd/system/update_network.service"

  - name: enable pull service
    systemd:
            name: update_shutdown.service
            enabled: yes
            masked: no

  - name: enable update network service
    systemd:
            name: update_network.service
            enabled: yes
            masked: no
