---
- hosts: 127.0.0.1
  remote_user: sysadmin
  become: yes
  tasks:
  - name: manage /etc/ldap.conf via debconf
    debconf:
        name: "{{ item.name }}"
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
    loop:
        - {name: 'ldap-auth-config',
        question: 'ldap-auth-config/ldapns/ldap-server',
        value: 'ldap://ldap.math.uni-sb.de ldap://ldap-slave-1.math.uni-sb.de ldap://ldap-slave-2.math.uni-sb.de',
        vtype: 'string'}
        - {name: 'ldap-auth-config',
        question: 'ldap-auth-config/ldapns/base-dn',
        value: 'dc=math,dc=uni-sb,dc=de',
        vtype: 'string'}
        - {name: 'ldap-auth-config',
        question: 'ldap-auth-config/ldapns/ldap_version',
        value: '3',
        vtype: 'string'}
        - {name: 'ldap-auth-config',
        question: 'ldap-auth-config/pam_password',
        value: 'md5',
        vtype: 'select'}
        - {name: 'ldap-auth-config',
        question: 'ldap-auth-config/move-to-debconf',
        value: 'true',
        vtype: 'boolean'}
        - {name: 'ldap-auth-config',
        question: 'ldap-auth-config/dblogin',
        value: 'false',
        vtype: 'boolean'}
        - {name: 'ldap-auth-config',
        question: 'ldap-auth-config/dbrootlogin',
        value: 'false',
        vtype: 'boolean'}
        - {name: 'ldap-auth-config',
        question: 'ldap-auth-config/override',
        value: 'true',
        vtype: 'boolean'}
  - name: generate /etc/nsswitch.conf
    template:
        src: nsswitch.j2
        dest: /etc/nsswitch.conf
  - name: ensure that base packages for LDAP are installed
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - aptitude
        - libnss-ldap
        - libpam-ldap
        - nscd
        - portmap

  - name: replace /etc/pam.d/common-session
    template:
        src: common-session.j2
        dest: /etc/pam.d/common-session
