---
- hosts: 127.0.0.1
  remote_user: sysadmin
  become: yes
  tasks:
  - name: ensure that base packages for LDAP are installed
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - aptitude
        - libnss-ldap
        - libpam-ldap
        - nscd
        - portmap
        - oddjob-mkhomedir

  - name: relevant configs for LDAP
    debconf:
        name: "{{ item.name }}"
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
    loop:
        - {name: 'ldap-auth-config',
        question: 'ldapns/ldap-server',
        value: 'ldap://ldap.math.uni-sb.de ldap://ldap-slave-1.math.uni-sb.de ldap://ldap-slave-2.math.uni-sb.de',
        vtype: 'string'}
        - {name: 'ldap-auth-config',
        question: 'ldapns/base-dn',
        value: 'dc=math,dc=uni-sb,dc=de',
        vtype: 'string'}
