---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - name: update known hosts
    copy:
            src: "known_hosts.j2"
            dest: "/etc/ssh/ssh_known_hosts"

  - name: upgrade machine
    apt:
            upgrade: dist
            update_cache: yes

  - name: update init playbook
    synchronize:
            src: "update_network"
            dest: "/usr/share/ansible"
            perms: yes
            recursive: yes
            delete: yes

  - name: install packages
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: no
    vars:
        packages:
        - texmaker
        - texstudio
        - vlc
        - kile
        - libreoffice
        - gvfs-backends
        - gvfs-fuse
        - emacs
        - gnome-calculator
