---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - name: upgrade machine
    apt:
            upgrade: dist
            update_cache: yes

  - name: update init playbook
    copy:
            src: "update_network"
            dest: "/usr/share/ansible"

  - name: include group specific tasks
    include_tasks: "{{ group_server }}.yml"
    when: group_server is defined
