---
- hosts: 127.0.0.1
  remote_user: sysadmin
  become: yes
  tasks:
  - name: ensure that base packages for sshfs are installed
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - sshfs
        - libpam-mount

  - name: replace /etc/security/pam_mount.conf.xml
    template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
    loop:
            - {src: 'pam_mount.conf.j2',
              dest: '/etc/security/pam_mount.conf.xml'}
            - {src: 'resetHome.j2',
              dest: '/etc/profile.d/resetHome.sh'}
