---
- hosts: all
  vars:
    gate: "{{ ansible_default_ipv4.gateway }}"
    gate_mg: "{{ '134.96.64.225' | ipaddr }}"
    gate_rs: "{{ '134.96.28.225' | ipaddr }}"
  remote_user: sysadmin
  become: yes
  tasks:
  - set_fact:
        group_server: "d9-mg"
    when: gate == gate_mg
  - name: ensure that base packages for sshfs are installed
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - sshfs
        - libpam-mount

  - name: generate right config files
    template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
    loop:
            - {src: 'pam_mount.conf.j2',
              dest: '/etc/security/pam_mount.conf.xml'}
            - {src: 'resetHome.j2',
              dest: '/etc/profile.d/resetHome.sh'}
            - {src: 'switchCups.j2',
              dest: '/etc/profile.d/switchCups.sh'}
            - {src: 'known_hosts.j2',
              dest: '/etc/ssh/ssh_known_hosts'}
            - {src: 'common-auth.j2',
              dest: '/etc/pam.d/common-auth'}
            - {src: 'locale.j2',
              dest: '/etc/default/locale'}
