---
- hosts: all
  remote_user: sysadmin
  become: yes
  tasks:
  - name: install base packages
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - firefox
        - thunderbird
        - gnome-terminal
        - gedit
        - evince
        - eog
        - x2goclient
        - texlive-latex-extra
        - texlive-science
        - texlive-bibtex-extra
        - texlive-lang-german
        - texlive-lang-english
        - texlive-pstricks
        - texlive-publishers
        - texlive-luatex
  - name: get matlab and maple icons
    get_url: "{{ item.url }}"
    dest: "/usr/share/icons/{{ item.name }}"
    loop:
           - {url: 'https://www.math.uni-sb.de/ag/groves/Matlab_Logo.png',
             name: 'matlab.png'}
           - {url: 'https://www.math.uni-sb.de/ag/groves/Maple_lg.png',
             name: 'maple.png'}
