---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - name: install base packages
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - firefox
        - thunderbird
        - gnome-terminal
        - gedit
        - evince
        - eog
        - x2goclient
        - pyhoca-cli
        - libreoffice
        - texlive-latex-extra
        - texlive-science
        - texlive-bibtex-extra
        - texlive-lang-german
        - texlive-lang-english
        - texlive-pstricks
        - texlive-publishers
        - texlive-luatex
        - texstudio
        - kile
        - emacs
