---
- hosts: mg
  remote_user: sysadmin
  become: yes
  tasks:
  - name: install specific packages
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
        - firefox
        - thunderbird
        - gnome-terminal
        - gedit
        - x2goclient
        - texlive-latex-extra
        - texstudio
        - texlive-science
        - texlive-bibtex-extra
        - texlive-lang-german
        - texlive-lang-english
        - texlive-pstricks
        - texlive-publishers
        - texlive-luatex
