---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - set_fact:
     group_server: "{{ item.group_server }}"
    when: ansible_default_ipv4.gateway ==  item.gate
    loop:
        - {gate: '{{ "134.96.64.225" | ipaddr }}',
          group_server: 'd9-mg'}
        - {gate: '{{ "134.96.28.225" | ipaddr }}',
          group_server: 'd9-rs'}
  - name: update config files
    template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
    loop:
            - {src: 'pam_mount.conf.j2',
              dest: '/etc/security/pam_mount.conf.xml'}
            - {src: 'locale.j2',
              dest: '/etc/default/locale'}
            - {src: 'sessions.j2',
              dest: '/usr/share/x2goclient/sessions'}
            - {src: 'matlab.j2',
              dest: '/usr/share/applications/matlab-{{ group_server }}.desktop'}
            - {src: 'maple.j2',
              dest: '/usr/share/applications/maple-gemini.desktop'}
  - name: include group specific tasks
    include_tasks: "{{ group_server }}.yml"
    when: group_server is defined
