---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - set_fact:
     group_server: "{{ item.group_server }}"
    when: ansible_default_ipv4.gateway ==  item.gate
    loop:
        - {gate: '{{ "134.96.64.225" | ipaddr }}',
          group_server: 'd9-mg'}
        - {gate: '{{ "134.96.28.225" | ipaddr }}',
          group_server: 'd9-rs'}
  - name: ensure cron for root is gone
    cron:
            name: "pull at reboot"
            state: absent
  - name: set a cron for ansible-pull at reboot
    cron:
            name: "pull at reboot"
            user: sysadmin
            special_time: reboot
            job: "ansible-pull -o -u sysadmin -U https://github.com/bhewer/ansible.git -i hosts update.yml"
  - name: set a cron for ansible-pull at 2am
    cron:
            name: "pull at 2am"
            user: sysadmin
            minute: "0"
            hour: "2"
            job: "ansible-pull -o -u sysadmin -U https://github.com/bhewer/ansible.git -i hosts update.yml"
  - name: update config files
    template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
    loop:
            - {src: 'pam_mount.conf.j2',
              dest: '/etc/security/pam_mount.conf.xml'}
            - {src: 'locale.j2',
              dest: '/etc/default/locale'}
            - {src: 'sessions.j2',
              dest: '/usr/share/x2goclient/sessions'}
            - {src: 'matlab.j2',
              dest: '/usr/share/applications/matlab-{{ group_server }}.desktop'}
            - {src: 'maple.j2',
              dest: '/usr/share/applications/maple-gemini.desktop'}
  - name: include group specific tasks
    include_tasks: "{{ group_server }}.yml"
    when: group_server is defined
