---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - set_fact:
     group_server: "{{ item.group_server }}"
    when: ansible_default_ipv4.gateway ==  item.gate
    loop:
        - {gate: '{{ "134.96.64.225" | ipaddr }}',
          group_server: 'd9-mg'}
        - {gate: '{{ "134.96.28.97" | ipaddr }}',
          group_server: 'd9-rs'}
        - {gate: '{{ "134.96.28.33" | ipaddr }}',
          group_server: 'd9-fs'}
        - {gate: '{{ "134.96.13.65" | ipaddr }}',
          group_server: 'd9-cb'}
        - {gate: '{{ "134.96.28.193" | ipaddr }}',
          group_server: 'd9-sb'}
        - {gate: '{{ "134.96.28.1" | ipaddr }}',
          group_server: 'd9-je'}
        - {gate: '{{ "134.96.28.161" | ipaddr }}',
          group_server: 'd9-mf'}
        - {gate: '{{ "134.96.28.225" | ipaddr }}',
          group_server: 'd9-gw'}
  - set_fact:
     group_server: "gemini"
    when: group_server is undefined

  - name: install remote key script
    copy:
            src: "generate_remoteKey.sh"
            dest: "/usr/local/bin/generate_remoteKey"
            mode: "+x"

  - name: install remote script
    copy:
            src: "start_remote.sh"
            dest: "/usr/local/bin/start_remote"
            mode: "+x"

  - name: update config files
    template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
    loop:
            - {src: 'pam_mount.conf.j2',
              dest: '/etc/security/pam_mount.conf.xml'}
            - {src: 'sessions.j2',
              dest: '/usr/share/x2goclient/sessions'}
            - {src: 'maple.j2',
              dest: '/usr/share/applications/maple-gemini.desktop'}
  - name: include d9 app specific taks
    include_tasks: "d9-apps/create_links.yml"

