---
- hosts: 127.0.0.1
  connection: local
  remote_user: sysadmin
  become: yes
  tasks:
  - set_fact:
     group_server: "{{ item.group_server }}"
    when: ansible_default_ipv4.gateway ==  item.gate
    loop:
        - {gate: '{{ "134.96.64.225" | ipaddr }}',
          group_server: 'd9-mg'}
        - {gate: '{{ "134.96.28.97" | ipaddr }}',
          group_server: 'd9-rs'}
  - set_fact:
     group_server: "gemini"
    when: group_server is undefined
  - name: install remote script
    copy:
            src: "start_remote.sh"
            dest: "/usr/bin/start_remote"

  - name: update config files
    template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
    loop:
            - {src: 'pam_mount.conf.j2',
              dest: '/etc/security/pam_mount.conf.xml'}
            - {src: 'sessions.j2',
              dest: '/usr/share/x2goclient/sessions'}
            - {src: 'matlab.j2',
              dest: '/usr/share/applications/matlab-d9.desktop'}
            - {src: 'maple.j2',
              dest: '/usr/share/applications/maple-gemini.desktop'}
  - name: update d9 apps
    template:
            src: "d9-app.j2"
            dest: "/usr/share/applications/{{ item.name }}-d9.desktop"
    loop:
            - {name: 'matlab',
              command: 'matlab -desktop'}
